version: "3.8"

services:
  backend:
    build:
      context: .
      target: base
    command:
      - make
      - dev
    ports:
      - "8080:8080/tcp"
    volumes:
      - source: .
        target: /app
        type: bind
    develop:
      watch:
        - action: rebuild
          path: ./go.mod
    environment:
      LOG_LEVEL: debug
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:8.0.2-bookworm@sha256:b43d2dcbbdb1f9e1582e3a0f37e53bf79038522ccffb56a25858969d7a9b6c11
    ports:
      - "6379:6379/tcp"
