version: "3.8"

services:
  backend:
    build:
      context: .
      target: base
    command:
      - make
      - dev
    ports:
      - "8080:8080/tcp"
    volumes:
      - source: .
        target: /app
        type: bind
    develop:
      watch:
        - action: rebuild
          path: ./go.mod
    environment:
      LOG_LEVEL: debug
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:8.2.3-bookworm@sha256:5c7c0445ed86918cb9efb96d95a6bfc03ed2059fe2c5f02b4d74f477ffe47915
    ports:
      - "6379:6379/tcp"
