version: "3.8"

services:
  backend:
    build:
      context: .
      target: base
    command:
      - make
      - dev
    ports:
      - "8080:8080/tcp"
    volumes:
      - source: .
        target: /app
        type: bind
    develop:
      watch:
        - action: rebuild
          path: ./go.mod
    environment:
      LOG_LEVEL: debug
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:8.2.2-bookworm@sha256:4521b581dbddea6e7d81f8fe95ede93f5648aaa66a9dacd581611bf6fe7527bd
    ports:
      - "6379:6379/tcp"
