// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/SlashNephy/discord-broadcaster/config"
	"github.com/SlashNephy/discord-broadcaster/infrastructure/external/discord"
	"github.com/SlashNephy/discord-broadcaster/infrastructure/repository"
	"github.com/SlashNephy/discord-broadcaster/usecase"
	"github.com/SlashNephy/discord-broadcaster/web"
	"github.com/SlashNephy/discord-broadcaster/web/controller"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context, cfg *config.Config, redis2 *redis.Client) (*web.Server, error) {
	webConfig := &cfg.ServerConfig
	usecaseConfig := &cfg.UsecaseConfig
	messageRepository := repository.NewMessageRepository(redis2)
	discordConfig := &cfg.DiscordConfig
	service, err := discord.NewService(discordConfig)
	if err != nil {
		return nil, err
	}
	usecaseService := usecase.NewService(ctx, usecaseConfig, messageRepository, service)
	controllerController := controller.NewController(usecaseService)
	server, err := web.NewServer(webConfig, controllerController)
	if err != nil {
		return nil, err
	}
	return server, nil
}
